2024-03-09 024b: .
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for tripleo.elijah:tripleo.elijah.core:jar:congenial.2023-12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ tripleo.elijah:congenial-robot:congenial.2023-12, /home/generic/IdeaProjects/congenial-robot/pom.xml, line 166, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for tripleo.elijah:congenial-robot:pom:congenial.2023-12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 166, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] eljc-almost-congenial-robot                                        [pom]
[INFO] tripleo.elijah.core                                                [jar]
[INFO]
[INFO] -------------------< tripleo.elijah:congenial-robot >-------------------
[INFO] Building eljc-almost-congenial-robot congenial.2023-12             [1/2]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] -----------------< tripleo.elijah:tripleo.elijah.core >-----------------
[INFO] Building tripleo.elijah.core congenial.2023-12                     [2/2]
[INFO]   from elijah-core/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.osgi:org.osgi.service.prefs:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO]
[INFO] --- xtend:2.34.0:compile (default) @ tripleo.elijah.core ---
[ERROR]
ERROR:  _GenerateC_T.xtend - /home/generic/IdeaProjects/congenial-robot/elijah-core/src/main/java/tripleo/elijah/stages/gen_c/internal_t/_GenerateC_T.xtend
12: tripleo.elijah.stages.gen_fn.tripleo.elijah.stages.gen_fn.IBaseEvaFunction cannot be resolved to a type.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eljc-almost-congenial-robot congenial.2023-12:
[INFO]
[INFO] eljc-almost-congenial-robot ........................ SUCCESS [  0.078 s]
[INFO] tripleo.elijah.core ................................ FAILURE [  7.872 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.060 s
[INFO] Finished at: 2024-03-10T01:01:32-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.34.0:compile (default) on project tripleo.elijah.core: Error compiling xtend sources in '/home/generic/IdeaProjects/congenial-robot/elijah-core/src/main/java'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :tripleo.elijah.core